### ISSUE TITLE
Socket.io-emitter and Heroku

### ISSUE THREAD

**Issue by zacharynevin** [socketio/socket.io-emitter#13]
The app I have on my local machine can use websockets just fine. I am using a windows machine with socket.io and Redis (but not hiredis).

The application on Heroku can receive websocket events just fine. I can see this in the logs. The problem is when I use socket.io-emitter to emit events back to the client. Basically, nothing happens at all. Nothing shows up in the logs, and there are no errors thrown.

**Comment by hidalgofdz** [comment]
I know its kind of late but what did you mean with a "new redis client"? @zacharynevin

**Comment by senica** [comment]
```
var client = require('redis').createClient({
  host: '<your host>',
  port: 6379,
  password: '<your password>',
});
```

**Comment by SobakaSlava** [comment]
https://github.com/socketio/socket.io-emitter/pull/79
this contains a fix
