### ISSUE TITLE
Emitting to more than one room at a time, defaults redis channel name back to socket.io#/#

### ISSUE THREAD

**Issue by ambrosestartup** [socketio/socket.io-emitter#131]
Hi guys,

I am currently sending data to two rooms using this method from the docs:
```
io.to('room1').to('room2').to('room3').emit('some event');
```

I am looking to find the data in Redis searching for the channel using the room name ( e.g. the channel should look something like "socket.io#/#room1#" and "socket.io#/#room2#" ). I think however when the room size is > 1 then it defaults back to socket.io#/#. 

Is this intended? I can see the code in the library that exhibits the behaviour.
```
        const msg = this.broadcastOptions.parser.encode([UID, packet, opts]);
        let channel = this.broadcastOptions.broadcastChannel;
        console.log("channel")
        console.log(channel)
        if (this.rooms && this.rooms.size === 1) {
            channel += this.rooms.keys().next().value + "#";
        }
        console.log(channel)
        debug("publishing message to channel %s", channel);
        this.redisClient.publish(channel, msg);
        return `true;`
```
Which is in index.js in the "emit" method around lines 260-270. 

I have defaulted back to sending two emits now and not chaining the "to" methods, which creates the correct redis channel names. 

I personally think you should be able to send to multiple rooms and listen to those in redis with the correct channel names - is this an issue we can solve ?

**Comment by darrachequesne** [comment]
Hi!

> I think however when the room size is > 1 then it defaults back to `socket.io#/#`

Yes, that is the intended behavior.

This is needed to ensure that an event sent to multiple rooms will only be received once by a given client, even if it is in more than one targeted room.

Does it cause any performance issue in your application?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
