### ISSUE TITLE
Emitting events to the server side of socket.io

### ISSUE THREAD

**Issue by xfg** [socketio/socket.io-emitter#20]
How to emit an event to the server side of socket.io ? This library enables to emit an event to the client side of socket.io, but I want to emit an event to the server side of socket.io too.

Sorry for my bad English.

**Comment by nodecode** [comment]
You need to use <code>socket.io-client</code>, which can be used on the server side. See: https://github.com/socketio/socket.io-client#nodejs-server-side-usage
