### ISSUE TITLE
Flags is not work

### ISSUE THREAD

**Issue by xfg** [socketio/socket.io-emitter#21]
var io = require('socket.io-emitter')({ host: '127.0.0.1', port: 6379 });
io.broadcast.emit('event', 'data');

the broadcast flag is ignored, same with the other flags.

**Comment by darrachequesne** [comment]
Well, if I understand correctly, `broadcast` is quite useless here, since every packet is always broadcast, either to a given room or to the whole namespace.

The `volatile` flag should work though.
