### ISSUE TITLE
Cut new release to get rid of npm’s No repo warning

### ISSUE THREAD

**Issue by stiang** [socketio/socket.io-emitter#22]
I see that you added a repo field to package.json quite some time ago, so it would be really appreciated if you could push a new version to npm, so that the warning goes away.

Not a high priority issue, of course, it just bugs me :)

**Comment by shnist** [comment]
+1

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-emitter/pull/12 (released as `0.3.0`)
