### ISSUE TITLE
Incompatible with Newest socket.io-redis Commits

### ISSUE THREAD

**Issue by night** [socketio/socket.io-emitter#25]
Since socket.io-redis now emits to specific namespaces and rooms, the socket.io-emitter is not compatible with the latest changes.

https://github.com/Automattic/socket.io-redis/blob/c07b3bdaef579fbe963170b9ad490b656d31494c/index.js#L122

**Comment by jdesboeufs** [comment]
Can you write a test for that?

**Comment by aPoCoMiLogin** [comment]
They fix that https://github.com/socketio/socket.io-emitter/commit/e656600388bdb3fc1cf62331e18d1a6a7775ab36 https://github.com/socketio/socket.io-redis/issues/78

**Comment by night** [comment]
This is fixed by 5e26420d3e41fb3acf02d4217adf9a6c6f097f6d
