### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by CrackerakiUA** [socketio/socket.io-emitter#29]
I have  `
var redis = require('socket.io-redis');io.adapter(redis({ host: 'hhhhh', port: xxxx}));` which is connecting normally and when i use `var emiter = require('socket.io-emitter')({ host: 'hhhhh', port: xxxx });` this got timout error. Both those are in the same file `app.js`.

**Comment by mavrick** [comment]
Try this:

```javascript
var redis = require('socket.io-redis');
var pub = redis.createClient("port", "host", {auth_pass: "optionalPassword"});
var emitter = require('socket.io-emitter')(pub);
```

**Comment by CrackerakiUA** [comment]
ETIMEDOUT

**Comment by mdw19873** [comment]
Has anyone determined the cause for this? I've tried newer versions of redis and even emitting an event every 5 seconds and I still get ETIMEDOUT
