### ISSUE TITLE
Cannot capture room event using the standard io.sockets.in("room").on("event",function(){})

### ISSUE THREAD

**Issue by magestican** [socketio/socket.io-emitter#30]
I am using this emitter alongside the redis socket.io adapter in order to scale my servers, the thing is that I am not able to intercept events from serverA in serverB, the event goes through to the clients of serverB but cant intercept it using the standard  : 
 io.sockets.in("room").on("event",function(){})

any idea why? is there something like emitter.in("room").on("event",handler) ?

thank you! :+1:

**Comment by darrachequesne** [comment]
As far as I know, that package is meant to publish packets, not subscribe.

Also, `io.sockets.in("room").on("event",function(){})` looks weird, the event listener should be registered on each socket, shouldn't it?
