### ISSUE TITLE
This library is emitting to everyone in a particular room AND everyone else not in a room

### ISSUE THREAD

**Issue by magestican** [socketio/socket.io-emitter#32]
This is related to this code which doesnt filter out rooms in order to send messages : 

// publish
143   if (opts.rooms && opts.rooms.length) {
144     opts.rooms.forEach(function(room) {
145       var chnRoom = chn + room + '#';
146       self.redis.publish(chnRoom, msg);
147     });
148   } else {
149     this.redis.publish(chn, msg);
150   }

**Comment by darrachequesne** [comment]
Could you please give more details? I'm afraid I don't understand the issue here.
