### ISSUE TITLE
Emitter.prototype.of should return a new Emitter instance

### ISSUE THREAD

**Issue by travellingprog** [socketio/socket.io-emitter#34]
It would be great to be able to do something like this:

```
var io = require('socket.io-emitter')({ host: '127.0.0.1', port: 6379 });
var nspEmitter = io.of('/someNamespace');
```

... and then be able to use `nspEmitter` **multiple times** afterwards to do actions related to that namespace. That would make it behave similarly to the `of()` function of SocketIO itself: http://socket.io/docs/rooms-and-namespaces/#custom-namespaces

Instead, for socket.io-emitter, the `of()` function needs to be used before each `emit()`. This inconsistency between SocketIO and socket.io-emitter leads to some confusion. At the very least, the documentation should state that `of()` needs to be called before each `emit()`.

**Comment by DimaIT** [comment]
It take a lot of time to investigate this for me. Hope that will be fixed.

**Comment by darrachequesne** [comment]
@travellingprog I'll be happy to merge your pull request!

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-emitter/pull/56.
