### ISSUE TITLE
why cannot emitter join room?

### ISSUE THREAD

**Issue by laizhenhai88** [socketio/socket.io-emitter#36]
hi, 
in my server process, user send his gps and i broadcast it to room 'position'

> 
socket.on('position',(gps)=>{
 io.to('position').emit(someone's gps);
})

and i want to collect all the gps in my emitter process
if i can use:

> 
var io = require('socket.io-emitter')({ host: '127.0.0.1', port: 6379 });
io.join('position');
io.on('position',(data)=>{
//collect everyone's gps to one object
});

so that, i can broadcast everyone's gps every 5s in room 'gps'
if someone care, he can join room 'gps'
setInterval(function(){
    io.to('gps').emit('all position', 'data');
}, 5000);

so, my question is why cannot emitter join room? is there any other better solution?

**Comment by mavrick** [comment]
Hi @laizhenhai88,

Did you end up answering your own question? If so, what solutions did you take?


Cheers

**Comment by laizhenhai88** [comment]
@mavrick 
i solve it myself, here is the code
[https://github.com/laizhenhai88/emitter](https://github.com/laizhenhai88/emitter)
