### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by betimer** [socketio/socket.io-emitter#38]
Logs are below:

rtcblue-1 (err):     at E:\Go Agent\pipelines\Blue-Build-Deploy-RTCIO-Signaller\node_modules\socket.io\lib\namespace.js:
174:14
rtcblue-1 (err):     at _combinedTickCallback (node.js:370:9)
rtcblue-1 (err):     at process._tickDomainCallback (node.js:425:11)
rtcblue-1 (err): error: Socket.io (peer) says: disconnected with connection id /#d5TphKlO9tOdVL-FAAAI
rtcblue-1 (err): error: Socket.io (peer) says: disconnected with connection id /#sttO417fZ8X1fZBlAAAH
rtcblue-1 (err): (node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMax
Listeners() to increase limit.
rtcblue-1 (err): Trace
rtcblue-1 (err):     at EventEmitter.addListener (events.js:252:17)
rtcblue-1 (err):     at Object.announce._.board.on [as announce](E:Go AgentpipelinesBlue-Build-Deploy-RTCIO-Signalle
rtargetwebrtcswitchBoardHandlerscall.js:60:15)
rtcblue-1 (err):     at doThisWithPeer (E:\Go Agent\pipelines\Blue-Build-Deploy-RTCIO-Signaller\target\webrtc\mainSwitch
.js:40:32)
rtcblue-1 (err):     at Namespace.<anonymous> (E:\Go Agent\pipelines\Blue-Build-Deploy-RTCIO-Signaller\target\webrtc\soc
ketHandlers\peer.js:11:9)
rtcblue-1 (err):     at emitOne (events.js:90:13)
rtcblue-1 (err):     at Namespace.emit (events.js:182:7)
rtcblue-1 (err):     at Namespace.emit (E:\Go Agent\pipelines\Blue-Build-Deploy-RTCIO-Signaller\node_modules\socket.io\l
ib\namespace.js:206:10)
rtcblue-1 (err):     at E:\Go Agent\pipelines\Blue-Build-Deploy-RTCIO-Signaller\node_modules\socket.io\lib\namespace.js:
174:14
rtcblue-1 (err):     at _combinedTickCallback (node.js:370:9)
rtcblue-1 (err):     at process._tickDomainCallback (node.js:425:11)
rtcblue-1 (err): error: Socket.io (peer) says: disconnected with connection id /#QqDHc_MsT1dffS0NAAAJ
rtcblue-1 (err): error: Socket.io (peer) says: disconnected with connection id /#BQFBtMezSBtDaPw4AAAL
rtcblue-1 (err): error: Socket.io (peer) says: disconnected with connection id /#9r11P2ZNFBhaACF6AAAK

**Comment by darrachequesne** [comment]
It seems there's a lot of listeners registered, were you able to locate the problem?
