### ISSUE TITLE
Allow passing a REDIS_URL

### ISSUE THREAD

**Issue by darkpixel** [socketio/socket.io-emitter#40]
Support passing in a REDIS_URL.

i.e. process.env.REDIS_URL === 'redis://:secrets@example.com:1234'

**Comment by davidgatti** [comment]
Agree

**Comment by davidgatti** [comment]
@darkpixel check my pull request. It is actually one line of code change, so even if this pull request won't be accepted you can easily modify the source code of this module in your project :)

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-emitter/pull/41 (released as `1.1.0`)
