### ISSUE TITLE
Cannot send callbacks when emitting to single socket

### ISSUE THREAD

**Issue by ismail-khan** [socketio/socket.io-emitter#50]
Running Heroku with multiple dynos, and using `socket.io-emitter` with `socket.io-redis`.

So far, I am able to emit events to specific connected clients using `emitter.to(socketId).emit(...)`.

However, I'm trying to do `emitter.to(socketId).emit('event', function(){...})`, but the callback function is never sent to the client. Any other type of argument is successfully sent, but callback functions show up as undefined.

Is this by design? If so, is there any chance of this being introduced in a future update? I'm relying on callbacks quite a bit and am trying to avoid abandoning them.

**Comment by darrachequesne** [comment]
As far as I know, acknowledgements are not supported when broadcasting, so I'm afraid you'll have to build your own system for that.

**Comment by ismail-khan** [comment]
Seems like it's a deliberate limitation of functionality. Would be really nice to have it, but oh well...
