### ISSUE TITLE
Does it support Acknowledgement as in main Socket.io emitter?

### ISSUE THREAD

**Issue by subenksaha** [socketio/socket.io-emitter#51]
I am trying to pass acknowledgement function while emitting to client but it's not working but in socket.io node process it is working file. here is my code below:
```
io
.to(socketId)
.emit("event", data,function (err,message) {
     console.info(message);
     console.error(err);
});
```
the callback function is not called and in java client i am gutting ack function null.

**Comment by darrachequesne** [comment]
Duplicate of https://github.com/socketio/socket.io-emitter/issues/50.
