### ISSUE TITLE
lose namespace when emit multiple rooms

### ISSUE THREAD

**Issue by zhaolong06** [socketio/socket.io-emitter#52]
code:
```javascript
const rooms = ['room1', 'room2'];
const nsp = io.of('/some namespace');
for (let room of rooms) {
  nsp.to(room).emit('message', 'test');
}
```
the namespace of the second room will be lost

**Comment by darrachequesne** [comment]
That issue has already been identified: https://github.com/socketio/socket.io-emitter/issues/34

If anyone wants to refactor the code...
