### ISSUE TITLE
Question: Can Emitter get a list of rooms, or count of connections in a room?

### ISSUE THREAD

**Issue by Raukk** [socketio/socket.io-emitter#54]
I have a backed server that is processing Data and I need to know if anyone is still in a room before I process the data for that room (no point doing work if no one is listening). I don't really want to have the full Socket.io(+redis) service running since the back-end server cannot receive client http requests / websockets. 
Thanks.

I'm Running in Node.js on Heroku.

**Comment by darrachequesne** [comment]
@Raukk no, there is currently no way to do that with the `socket.io-emitter`. 

Related: https://github.com/socketio/socket.io-redis/pull/168

**Comment by Raukk** [comment]
Ok, Thanks.

**Comment by yogeshnarayanan** [comment]
@darrachequesne Is there better way to check if room exists from emitter process, when using multiple servers with Redis adapter
