### ISSUE TITLE
Emit Array Buffer does not send as Binary.

### ISSUE THREAD

**Issue by Raukk** [socketio/socket.io-emitter#58]
I'm trying to send an ArrayBuffer as binary to the client, my code worked when using the normal socket.io but Emitter sends the Array Buffer as JSON which is much less efficient bandwidth wise. 
Shouldn't Emit work the same for socket.io as socket.io-emiter? 

My socket.io-emitter code
```
//-----------my emitter code-------------//
    var nsp = io.of('/nsp');
    nsp.binaryType = 'arraybuffer';
//other stuff
    var send = new Float32Array(data);
    nsp.to(clientKey).emit("DataSend", send.buffer);
```
My old socket.io code
```
//-----------normal socket code-------------//
    var socket = io.of('/nsp');
    socket .binaryType = 'arraybuffer';
//other stuff
    var send = new Float32Array(data);
    socket.emit('DataSend', send.buffer);
```

**Comment by darrachequesne** [comment]
Hmm... couldn't you use the nodejs `Buffer` API instead? :smiley: 

I think there are a few issues here:
- `notepack.io` (now used in socket.io-redis / socket.io-emitter) does not support ArrayBuffer
```js
> const msgpack = require('notepack.io');
> msgpack.decode(msgpack.encode(Float32Array.of(4, 3, 2, 1)));
{ '0': 4, '1': 3, '2': 2, '3': 1 }
> msgpack.decode(msgpack.encode(Float32Array.of(4, 3, 2, 1).buffer));
{}
```
- `has-binary2` (used is [socket.io-parser](https://github.com/socketio/socket.io-parser/blob/3.1.2/index.js#L127)) does not support typed arrays
```js
> const hasBin = require('has-binary2');
> hasBin(Float32Array.of(4, 3, 2, 1))
false
> hasBin(Float32Array.of(4, 3, 2, 1).buffer)
true
```
- `isBuf` method ([link](https://github.com/socketio/socket.io-parser/blob/3.1.2/is-buffer.js)) does not support typed arrays either

**Comment by Raukk** [comment]
Thank you for the in-depth reply: 
I keep the data in a TypedArray for ease of use, but I use ".buffer" to get the array buffer when sending through socket.io.

I have tried Node Buffers (though I could have screwed it up):
`nsp.to(clientKey).emit("DataSend", Buffer.from(send.buffer));`
and on the client side I get:
`Object {type: "Buffer", data: Array(3072)}`
The problem is that the data is coming in as text/JSON and not as Binary data (therefor it is much larger, up to 4 times larger).
![image](https://cloud.githubusercontent.com/assets/11621499/26121765/f108a17a-3a3a-11e7-880a-3c21feccd077.png)


Using:
`nsp.to(clientKey).emit("DataSend", send.buffer);`
On the Client side I get:
`Object {}`
