### ISSUE TITLE
Send message to all clients except sender (like socket.broadcast.emit)

### ISSUE THREAD

**Issue by skkonstantin** [socketio/socket.io-emitter#65]
Is it possible to send a message to everyone except the sender?
I'm trying 
`io.broadcast.emit('message', 'test'),`
or
`io.of('/').broadcast.emit('message', 'test')`
but the message is coming to everyone including the sender

**Comment by darrachequesne** [comment]
Hi! What is the sender, in your case? `socket.io-emitter`?

**Comment by skkonstantin** [comment]
Hi!

https://socket.io/docs/server-api/#flag-broadcast

**Comment by raghavrarora310** [comment]
client.broadcast.emit indicates message is send to everyone except client 
                             OR
sender.broadcast.emit indicates message is send to everyone except sender

**Comment by MickL** [comment]
Hey @skkonstantin I dont understand. If you use socket.io-emitter then the sender (socket.io-emitter) is not using socket.io (just connected to Redis) and therefor will not receive its own message?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
