### ISSUE TITLE
How can we wait for emit() to finish?

### ISSUE THREAD

**Issue by jeremytm** [socketio/socket.io-emitter#66]
Hi team, we're using this with redis in an AWS lambda function which means we need to close connections and let lambda know we're done as soon as possible so they don't keep charging us.

Using your example code, sometimes we are seeing errors where the PUBLISH command is issued to redis after we've closed the redis connection because your example code is running synchronously.

How can we wait to ensure `.emit()` is done with redis before we wrap things up? I don't see any ability to assign a callback or use promises, etc.

Just to clarify, we don't need to wait for acknowledgement that the event has been received in other parts of the system, we just need to make sure the event has been sent into redis and that the PUBLISH command has succeeded.

**Comment by darrachequesne** [comment]
Hi! We could add a callback to the [publish](https://redis.io/commands/publish) method [here](https://github.com/socketio/socket.io-emitter/blob/3.1.0/index.js#L139), but that may indeed be mistaken for an actual acknowledgement (which is a bit harder to implement). What do you think?

**Comment by jeremytm** [comment]
Yeah you're right. A simple callback could be ambiguous with an acknowledgement callback.

What we did to solve this issue was forked the emitter file into our project and provided a promisified version of the function, so now we can just use `emitAsync()`.

The only other thing I can think of right now, would be to provide arguments as a object map of parameters, and then use object destructuring in the function definition but that would be a significant deviation from the general socket.io way of doing things.

**Comment by darrachequesne** [comment]
@jeremytm how about overloading the `publish` method? Something like:
```js
let pub = redis.createClient();
let doPublish = pub.publish;

pub.publish = (channel, msg) => {
  doPublish.call(pub, channel, msg, () => {
    // ok!
  });
};
```

**Comment by jeremytm** [comment]
That's a good idea. We'll switch to this at some point.

Thanks for your help! :)
