### ISSUE TITLE
How to disconnect?

### ISSUE THREAD

**Issue by josser** [socketio/socket.io-emitter#68]
Hi! 

Is there any way to disconnect from redis when I'm finish?
i.e: 

```javascript
const ioEmitter = require('socket.io-emitter')

const io = ioEmitter({ host: 'localhost', port: 6379 })
io.emit('test')

// io.close() or something?
```

this may be useful for cli tools, or in CI

**Comment by josser** [comment]
Actually, I need this only for auto-disconnect after tests running, so I've made this: https://github.com/socketio/socket.io-emitter/pull/69

**Comment by darrachequesne** [comment]
@josser I think you should rather provide your own redis client:
```js
const redisClient = createRedisClient();
const io = require('socket.io-emitter')(redisClient);
```

**Comment by josser** [comment]
Yes, I've tried this but I'm using babel / es6 modules and node_redis doesn't work if I'm using import.
So, I've used approach of express-session - they added 'unref' option.
(sorry, my english is probably not good)

**Comment by darrachequesne** [comment]
Well, in that case, I think the best would be to open an issue in `node_redis` repository. What do you think?

**Comment by josser** [comment]
@darrachequesne sure, will do, but having 'unref' option also very useful. take a look at https://github.com/tj/connect-redis

**Comment by darrachequesne** [comment]
Still, I'm not convinced we should use a "experimental" feature when there is a much cleaner solution..

**Comment by josser** [comment]
@darrachequesne I agree that 'experimental' features is not good
but it has been experimental for about 4 years. it has been added in node_redis v0.8.6 - October 2, 2013

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
