### ISSUE TITLE
Initialization error，ReplyError: Ready check failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by souljessi** [socketio/socket.io-emitter#75]
//test.js
var io = require('socket.io-emitter')({ host: '127.0.0.1', port: 6379, password: '123456'});

ReplyError: Ready check failed: NOAUTH Authentication required.

Is the field wrong? How should I write？

**Comment by igauravsehrawat** [comment]
I think it is bug, can confirm.
As a quick solution you should pass the created redis client as described in this [comment](https://github.com/socketio/socket.io-emitter/issues/13#issuecomment-347705075).

```
const redisClient = require('redis').createClient({...}); // pass auth, port, host here
const io = require('socket.io-emitter')(redisClient)
```

Cheers

**Comment by souljessi** [comment]
@igauravsehrawat 

You perfectly solved my problem, thank you！ 
Socket.io-emitter did not solve the password setting, so I had to create a redis instance。

Cheers。

**Comment by yuu2lee4** [comment]
i meet this problem,thanks the the comment.

**Comment by FireTable** [comment]
i meet this problem, thanks the the comment + 1.

**Comment by SobakaSlava** [comment]
FIx is in https://github.com/socketio/socket.io-emitter/pull/79
Need to merge

**Comment by darrachequesne** [comment]
As pointed out [here](https://github.com/socketio/socket.io-emitter/issues/75#issuecomment-395029305), passing your own Redis client is the way to go.

```js
const redisClient = require('redis').createClient({...}); // pass auth, port, host here
const io = require('socket.io-emitter')(redisClient);
```

I think the library shouldn't create a redis client by itself, as it gives false expectations to the user. The constructor `require('socket.io-emitter')({ host: '127.0.0.1', port: 6379 });` will be removed in the next major release.
