### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by agoenks29D** [socketio/socket.io-emitter#81]
i have run `npm install socket.io-emitter --save`

and try connect to server : 

```javascript
var io = require('socket.io-emitter')({ host: '127.0.0.1', port: 8081});
setInterval(function(){
  io.emit('time', new Date);
}, 5000);
```

and showing this error : 

![image](https://user-images.githubusercontent.com/11814324/56854324-bcfc3b80-695e-11e9-95ed-107f58e300b5.png)

when i try to install any package,i got problem : 

![image](https://user-images.githubusercontent.com/11814324/56854381-db166b80-695f-11e9-9f99-862ddfaf25be.png)

this library for client side or server side?

**Comment by KristjanTammekivi** [comment]
This library is for server side

**Comment by darrachequesne** [comment]
This library is indeed intended for server side usage. I've updated the README to make it clearer.
