### ISSUE TITLE
How do you implement and use this library?

### ISSUE THREAD

**Issue by 5haw4** [socketio/socket.io-emitter#84]
I've been trying for few days now to make this library work with my sockets in order to make an API call to an endpoint and from that endpoint emit a message to a certain user, I have to do it this way because I need to give the API endpoint to some service to use it as a webhook and emit the result to the user (So basically the user logs in with an outside service and performs an action in that service through my app, and once that action has been fulfilled by that other service I get an update to my API endpoint and from that endpoint I want to emit the message to the user to let them know about that and the part of emitting the message from the API endpoint process to the user's socket is what's causing me problems)

When I try to run this server it immediately gives me the following error:

> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

Here's my working code (This code works but it doesn't have the socket.io-emitter library so I can't emit a message to the socket from a non-socket process)

```
var express = require("express");
var app = express();
var http = require("http").createServer(app);
var io = require("socket.io")(http);

io.on("connection", (socket) => {
    console.log("User connected: ", socket.id);
    io.to(socket.id).emit("new_message", {id: "999", msg: "Welcome back, your Id is " + socket.id});
})

//here I want to emit a message to a user by the URL params
app.get("/send/:id/:message", (request, result) => {
    result.send("Id = " + request.params.id)
})

const port = 3001;
http.listen(port, () => {
    console.log("Listening to port " + port);
});
```

And this is how I tried to implement socket.io-emitter into the above code:

1.  Add the following code to the top of the script:
```
const redis = require('socket.io-redis');
io.adapter(redis('//localhost:6379'));
```

2. Add the following code inside the app.get("/send/:id/:message"....) function:
```
    const ioEmitter = require('socket.io-emitter')({ host: '127.0.0.1', port: 6379 });
    ioEmitter.to(request.params.id).emit({ id: "999", msg: request.params.message });
```
3. Here are the relevant depends I installed in this project while trying to make this library work, just so that you can see if I missed to install some libraries, or if there are some that collide:

>     "ioredis": "^4.14.1",
>     "redis": "^2.8.0",
>     "socket.io": "^2.3.0",
>     "socket.io-emitter": "^3.1.1",
>     "socket.io-redis": "^5.2.0"

I'd appreciate any attempt to help :)

**Comment by darrachequesne** [comment]
It seems your Redis server is not running. Could you please check?

Regarding the exception, you need to register an handler for the `error` event, more information here: https://github.com/socketio/socket.io-emitter#error-handling
