### ISSUE TITLE
Working with latest socket.io 3.x and Redis 6.x ?

### ISSUE THREAD

**Issue by MickL** [socketio/socket.io-emitter#88]
Hey,

this project has not been updated since 2017. I was wondering if it is still maintained and working with latest socket.io 3.x and Redis 6.x ?

Greetings

**Comment by darrachequesne** [comment]
Hi! The current version is compatible with both Socket.IO v2 (`socket.io-redis@5`) and Socket.IO v3 (`socket.io-redis@6`), as there was no update in the exchange protocol. I have updated the README to make it clearer.

Thanks!
