### ISSUE TITLE
Redis should not be a dependency

### ISSUE THREAD

**Issue by MickL** [socketio/socket.io-emitter#89]
May you add an example how to use with TypeScript? I tried both:

```
const io = require('socket.io-emitter')({ host: '127.0.0.1', port: 6379 });
```

and

```
import * as socketIoEmitter from 'socket.io-emitter';
const io = socketIoEmitter({ host: '127.0.0.1', port: 6379 });
```

but i get:

> ERROR in ./node_modules/socket.io-emitter/node_modules/redis-parser/lib/hiredis.js 3:14-32
Module not found: Error: Can't resolve 'hiredis' in '/Users/mick/git/myproject/node_modules/socket.io-emitter/node_modules/redis-parser/lib'

Btw. should `redis` be a peerDependency? I already have Redis in my project (v3) and socket.io-emitter imports v2 so I have two instances running.

**Comment by darrachequesne** [comment]
Hi! I could not reproduce the issue, both examples seem to work.

That's a bit weird though:
- `hiredis` is indeed required here: https://github.com/NodeRedis/node-redis-parser/blob/v.2.6.0/lib/hiredis.js#L3
- and the file is conditionally imported here: https://github.com/NodeRedis/node-redis-parser/blob/v.2.6.0/lib/parser.js#L344

But `hiredis` is not in the `dependencies` of the `redis-parser` package...

> should redis be a peerDependency?

I think it should even be in the `devDependencies` list, and let the user provide its own redis client.

```js
const io = require('socket.io-emitter')(redisClient, { /* additional options */});
```

But this change would need to be well documented..

> I already have Redis in my project (v3) and socket.io-emitter imports v2 so I have two instances running.

You should be able to create the emitter instance with a redis client v3 (the example above).

**Comment by MickL** [comment]
The problem are the dependencies: I already have redis v3 in my project and this package imports redis v2. If I change redis for this package to v3 then it works.

**Comment by MickL** [comment]
Hey @darrachequesne I see you updated the readme. Can we still remove redis from the dependencies and force the user to insert a client?

**Comment by darrachequesne** [comment]
Yes, let's do this :+1:

**Comment by darrachequesne** [comment]
Done in https://github.com/socketio/socket.io-emitter/commit/a70db12877d901dd0f7085def0a91145b7c83163.

You'll now need to explicitly install the `redis` package (or another compatible package like ioredis), and pass it in the Emitter constructor:

```js
const { Emitter } = require("socket.io-emitter");
const { createClient } = require("redis");

const redisClient = createClient();
const io = new Emitter(redisClient);
```

**Comment by MickL** [comment]
Thats nice! I did the same at nats-emitter https://github.com/MickL/socket.io-nats-emitter#readme
